shallow_clone: true

# http://help.appveyor.com/discussions/suggestions/419-qt-libraries
os: unstable

environment:
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 12"
    CMAKE_PREFIX_PATH: C:\Qt\5.4\msvc2013
  - CMAKE_GENERATOR: "Visual Studio 12 Win64"
    CMAKE_PREFIX_PATH: C:\Qt\5.4\msvc2013_64

matrix:
  fast_finish: true

configuration: Release

before_build:
- dir C:\Qt
- dir C:\Qt\5.4
- cmake -H. -Bbuild -G "%CMAKE_GENERATOR%" "-DCMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%"

build:
  project: build\apitrace.sln
  verbosity: minimal

post_build:
- cmake --build build --use-stderr --config "%CONFIGURATION%" --target package -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
