shallow_clone: true

environment:
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 12"
  - CMAKE_GENERATOR: "Visual Studio 12 Win64"

matrix:
  fast_finish: true

configuration: Release

before_build:
- cmake -G "%CMAKE_GENERATOR%" -H. -Bbuild

build:
- project: build\apitrace.sln
- verbosity: minimal

post_build:
- cmake --build build --use-stderr --config "%CONFIGURATION%" --target package -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
